### ISSUE TITLE
Doesn't change the Main Mirror on Linux Mint 19.3 Tricia

### ISSUE THREAD

**Issue by MarpleA** [martin68/apt-smart#4]
Hey, 

thanks for this great tool.

changing the Base Mirror for Bionic works flawless. Unfortunately it doesn't change the Main mirror on Linux Mint Tricia.

**Comment by martin68** [comment]
@MarpleA Sorry for late response. Unfortunately I don't have easy access to Linux Mint machines (even virtual machines) at the moment so I can't test. Any error log it said?
Thanks for feedback!

**Comment by martin68** [comment]
@MarpleA  Sorry for late fix, I've released new version 7.1.3, pls update & test. I'm closing this issue, pls reopen it if you find any related problem. THX!
